# 1. 붓꽃 데이터

## 학습 데이터로 잘못된 예측 케이스

In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

## 데이터 로드

In [7]:
iris = load_iris()

#학습 데이터 세팅
train_data = iris.data
train_label = iris.target

In [8]:
print(train_data.shape)
print(train_label.shape)

(150, 4)
(150,)


## 모델 학습

In [12]:
dt = DecisionTreeClassifier()
dt

DecisionTreeClassifier()

In [13]:
dt.fit(train_data, train_label)

DecisionTreeClassifier()

## 예측

In [15]:
y_pred = dt.predict(train_data)
print(f"예측 정확도 : {accuracy_score(train_label, y_pred)}")

예측 정확도 : 1.0


In [16]:
train_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 정확도 확인 시 1.0(100%)의 값이 나옴
## 과적합 되었음을 예측할 수 있고, 실제 값으로도 확인 가능
## train_test_split()을 이용해서 테스트셋의 비율을 나누어 확인

In [18]:
from sklearn.model_selection import train_test_split

In [22]:
iris = load_iris()

In [24]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                    test_size = 0.2,
                                                   random_state = 123)

In [25]:
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


In [26]:
dt1 = DecisionTreeClassifier()

In [28]:
dt1.fit(X_train, y_train)
# 예측정확도 확인
y_pred = dt1.predict(X_test)
print(f"예측정확도 : {accuracy_score(y_test, y_pred)}")

예측정확도 : 0.9666666666666667


## K-Fold 교차검증

In [29]:
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [30]:
# 데이터 로드
iris = load_iris()
label = iris.target
features = iris.data
print(features.shape)

(150, 4)


In [31]:
# 모델 정의
dt = DecisionTreeClassifier(random_state = 100)
dt

DecisionTreeClassifier(random_state=100)

In [34]:
# K-Fold
# 5개의 폴드세트로 분리하느 kfold 객체, 폴드 세트별 정확도 담을 리스트 객체 생성
kfold = KFold(n_splits = 5)
print(kfold)
# n_splits : 몇 개의 폴드로 분할할 지
# random_state = None : 나눈 Fold를 그대로 사용할 것인지
# shuffle : Fold로 나누기 전에 무작위 섞을 지

cv = []  # 5번 교차검증의 평균 정확도 계산하기 위한 리스트
print(f"붓꽃 데이터 셋트 크기 : {features.shape[0]}")

KFold(n_splits=5, random_state=None, shuffle=False)
붓꽃 데이터 셋트 크기 : 150


In [35]:
print(kfold.split(features)) #features 입력 데이터를 나타내는 변수
# .split() : 데이터를 분할하여 각 폴드의 인덱스를 반환

<generator object _BaseKFold.split at 0x000001EEF3204A60>


In [36]:
# kfold 객체의 split() 호출 학습, 검증 테스트의 행 인덱스를 array로 반환
for i in kfold.split(features):
    print(i)

(array([ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))
(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  60,  61,  62,  63,